# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3  # Or specify the version you're using

  - repo: https://gitlab.com/pycqa/flake8
    rev: 6.1.0  # Use the latest stable version
    hooks:
      - id: flake8
        additional_dependencies: ['flake8']  # Optional: add dependencies here
        args: ['--max-line-length=88']  # This is the default for Black

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true